-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.campaign
(
    cf_id integer NOT NULL,
    contact_id integer NOT NULL,
    company_name character varying(300) COLLATE pg_catalog."default" NOT NULL,
    description character varying(300) COLLATE pg_catalog."default" NOT NULL,
    goal double precision NOT NULL,
    pledged double precision NOT NULL,
    outcome character varying(300) COLLATE pg_catalog."default" NOT NULL,
    backers_count integer NOT NULL,
    country character varying(300) COLLATE pg_catalog."default" NOT NULL,
    currency character varying(300) COLLATE pg_catalog."default" NOT NULL,
    launched_date date NOT NULL,
    end_date date NOT NULL,
    category_id character varying(300) COLLATE pg_catalog."default" NOT NULL,
    subcategory_id character varying(300) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT campaign_pkey PRIMARY KEY (cf_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.category
(
    category_id character varying(150) COLLATE pg_catalog."default" NOT NULL,
    category character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (category_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.contacts
(
    contact_id integer NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT contacts_pkey PRIMARY KEY (contact_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.subcategory
(
    subcategory_id character varying(150) COLLATE pg_catalog."default" NOT NULL,
    subcategory character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT subcategory_pkey PRIMARY KEY (subcategory_id)
)
WITH (
    OIDS = FALSE
);

ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT campaign_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT campaign_contact_id_fkey FOREIGN KEY (contact_id)
    REFERENCES public.contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT campaign_subcategory_id_fkey FOREIGN KEY (subcategory_id)
    REFERENCES public.subcategory (subcategory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;